local M = {}

local shell_processes = {
  ['-zsh'] = true,
  zsh = true,
  ['-bash'] = true,
  bash = true,
  ['-fish'] = true,
  fish = true,
}

local function basename(path)
  return tostring(path or ''):match('([^/\\]+)$') or ''
end

local function safe_host(value)
  return type(value) == 'string' and value:match('^[%w%._@:%-]+$') ~= nil
end

local function safe_session(value)
  return type(value) == 'string' and value:match('^[%w%._%+%-]+$') ~= nil
end

-- Return a short, user-facing ssht invocation when argv contains the inline
-- resolver generated by zsh/ssht.zsh. The second return value distinguishes
-- an unrelated SSH command from a generated resolver that was unsafe to parse.
local function canonical_ssht_argv(argv)
  if type(argv) ~= 'table' or #argv < 4 then
    return nil, false
  end

  local remote_command = argv[#argv]
  if type(remote_command) ~= 'string' then
    return nil, false
  end

  local mode, encoded_session = remote_command:match('%s+ssht%s+(%a+)%s+(.+)$')
  if not mode then
    return nil, false
  end

  local host = argv[#argv - 1]
  if argv[2] ~= '-t' or not safe_host(host) then
    return nil, true
  end

  local short_argv = { 'ssht' }
  for i = 3, #argv - 1 do
    if type(argv[i]) ~= 'string' then
      return nil, true
    end
    table.insert(short_argv, argv[i])
  end

  if mode == 'default' and (encoded_session == "''" or encoded_session == '""') then
    return short_argv, true
  end

  if (mode == 'find' or mode == 'new') and safe_session(encoded_session) then
    -- A restored `new` session already exists, so reconnect by name instead of
    -- asking tmux to create it a second time.
    table.insert(short_argv, encoded_session)
    return short_argv, true
  end

  return nil, true
end

function M.restore_action(pane_tree)
  if not pane_tree or not pane_tree.alt_screen_active then
    return { kind = 'skip' }
  end

  local process = pane_tree.process
  if type(process) ~= 'table' then
    return { kind = 'skip' }
  end

  local process_name = basename(process.name ~= '' and process.name or process.executable)
  if shell_processes[process_name] then
    return { kind = 'skip' }
  end

  if process_name == 'ssh' then
    local argv, generated_ssht = canonical_ssht_argv(process.argv)
    if argv then
      return { kind = 'command', argv = argv }
    end
    if generated_ssht then
      return { kind = 'skip' }
    end
  end

  return { kind = 'default' }
end

return M
